//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YR_TM.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YR_TM.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址： 的本地化字符串。
        /// </summary>
        internal static string Address_Text {
            get {
                return ResourceManager.GetString("Address_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警信息 的本地化字符串。
        /// </summary>
        internal static string Alarm_Info {
            get {
                return ResourceManager.GetString("Alarm_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警代码 的本地化字符串。
        /// </summary>
        internal static string AlarmCode {
            get {
                return ResourceManager.GetString("AlarmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角度 的本地化字符串。
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取角度 的本地化字符串。
        /// </summary>
        internal static string Angle_Text {
            get {
                return ResourceManager.GetString("Angle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动刷新 的本地化字符串。
        /// </summary>
        internal static string AutoRefresh_Text {
            get {
                return ResourceManager.GetString("AutoRefresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率： 的本地化字符串。
        /// </summary>
        internal static string Baud_Text {
            get {
                return ResourceManager.GetString("Baud_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度 的本地化字符串。
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除报警 的本地化字符串。
        /// </summary>
        internal static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载 的本地化字符串。
        /// </summary>
        internal static string Btn_Load {
            get {
                return ResourceManager.GetString("Btn_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到此点位 的本地化字符串。
        /// </summary>
        internal static string Btn_MoveTo {
            get {
                return ResourceManager.GetString("Btn_MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string Btn_Query {
            get {
                return ResourceManager.GetString("Btn_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机参数 的本地化字符串。
        /// </summary>
        internal static string Camera_Text {
            get {
                return ResourceManager.GetString("Camera_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机控制 的本地化字符串。
        /// </summary>
        internal static string CameraControl_Text {
            get {
                return ResourceManager.GetString("CameraControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上拍照+取料X轴 的本地化字符串。
        /// </summary>
        internal static string CameraX_Text {
            get {
                return ResourceManager.GetString("CameraX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照+取料Z轴 的本地化字符串。
        /// </summary>
        internal static string CameraZ_Text {
            get {
                return ResourceManager.GetString("CameraZ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道： 的本地化字符串。
        /// </summary>
        internal static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信配置 的本地化字符串。
        /// </summary>
        internal static string Configuration_Text {
            get {
                return ResourceManager.GetString("Configuration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        internal static string Connect_Text {
            get {
                return ResourceManager.GetString("Connect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续 的本地化字符串。
        /// </summary>
        internal static string Continuou_Text {
            get {
                return ResourceManager.GetString("Continuou_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类型:  的本地化字符串。
        /// </summary>
        internal static string Device_Text {
            get {
                return ResourceManager.GetString("Device_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点胶X轴 的本地化字符串。
        /// </summary>
        internal static string DispensingX_Text {
            get {
                return ResourceManager.GetString("DispensingX_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点胶Z轴 的本地化字符串。
        /// </summary>
        internal static string DispensingZ_Text {
            get {
                return ResourceManager.GetString("DispensingZ_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 持续时间 的本地化字符串。
        /// </summary>
        internal static string Duration_Text {
            get {
                return ResourceManager.GetString("Duration_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string EndTime_Text {
            get {
                return ResourceManager.GetString("EndTime_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光时间 的本地化字符串。
        /// </summary>
        internal static string Exposure_Text {
            get {
                return ResourceManager.GetString("Exposure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        internal static string FileName_Text {
            get {
                return ResourceManager.GetString("FileName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HodlerY轴 的本地化字符串。
        /// </summary>
        internal static string HodlerY_Text {
            get {
                return ResourceManager.GetString("HodlerY_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片路劲： 的本地化字符串。
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO设置 的本地化字符串。
        /// </summary>
        internal static string IO_Text {
            get {
                return ResourceManager.GetString("IO_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态：连接正常 的本地化字符串。
        /// </summary>
        internal static string IOConnect_Text {
            get {
                return ResourceManager.GetString("IOConnect_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言选择： 的本地化字符串。
        /// </summary>
        internal static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总线：已连接 的本地化字符串。
        /// </summary>
        internal static string Lbl_Status_Connect {
            get {
                return ResourceManager.GetString("Lbl_Status_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总线：未连接 的本地化字符串。
        /// </summary>
        internal static string Lbl_Status_Not_Connect {
            get {
                return ResourceManager.GetString("Lbl_Status_Not_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Lbl_Time {
            get {
                return ResourceManager.GetString("Lbl_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择设备： 的本地化字符串。
        /// </summary>
        internal static string lblDevice_Text {
            get {
                return ResourceManager.GetString("lblDevice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源 的本地化字符串。
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源参数 的本地化字符串。
        /// </summary>
        internal static string Light_Text {
            get {
                return ResourceManager.GetString("Light_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光源控制 的本地化字符串。
        /// </summary>
        internal static string LightControl_Text {
            get {
                return ResourceManager.GetString("LightControl_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志路径： 的本地化字符串。
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统已启动 的本地化字符串。
        /// </summary>
        internal static string Log_SystemStart {
            get {
                return ResourceManager.GetString("Log_SystemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改时间 的本地化字符串。
        /// </summary>
        internal static string ModificationTime_Text {
            get {
                return ResourceManager.GetString("ModificationTime_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运动控制 的本地化字符串。
        /// </summary>
        internal static string Motion_Text {
            get {
                return ResourceManager.GetString("Motion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        internal static string Msg_SaveSuccess {
            get {
                return ResourceManager.GetString("Msg_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网卡选择： 的本地化字符串。
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径设置 的本地化字符串。
        /// </summary>
        internal static string Path_Text {
            get {
                return ResourceManager.GetString("Path_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照 的本地化字符串。
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位名称 的本地化字符串。
        /// </summary>
        internal static string Point_Text {
            get {
                return ResourceManager.GetString("Point_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点位调整 的本地化字符串。
        /// </summary>
        internal static string PointAdjustment {
            get {
                return ResourceManager.GetString("PointAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R轴 的本地化字符串。
        /// </summary>
        internal static string RAxis {
            get {
                return ResourceManager.GetString("RAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转R轴 的本地化字符串。
        /// </summary>
        internal static string RAxis_Text {
            get {
                return ResourceManager.GetString("RAxis_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新周期 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行模式: 的本地化字符串。
        /// </summary>
        internal static string Run_Mode {
            get {
                return ResourceManager.GetString("Run_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电批 的本地化字符串。
        /// </summary>
        internal static string Screwdriver {
            get {
                return ResourceManager.GetString("Screwdriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电批控制 的本地化字符串。
        /// </summary>
        internal static string Screwdriver_Text {
            get {
                return ResourceManager.GetString("Screwdriver_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电批操作 的本地化字符串。
        /// </summary>
        internal static string ScrewdriverOperation_Text {
            get {
                return ResourceManager.GetString("ScrewdriverOperation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态：空闲 的本地化字符串。
        /// </summary>
        internal static string ScrewStatu_Text {
            get {
                return ResourceManager.GetString("ScrewStatu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目录 的本地化字符串。
        /// </summary>
        internal static string SelectDirectory_Text {
            get {
                return ResourceManager.GetString("SelectDirectory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轴选择 的本地化字符串。
        /// </summary>
        internal static string Selection_Text {
            get {
                return ResourceManager.GetString("Selection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口号： 的本地化字符串。
        /// </summary>
        internal static string Serial_Text {
            get {
                return ResourceManager.GetString("Serial_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入信号 的本地化字符串。
        /// </summary>
        internal static string Signal_Text {
            get {
                return ResourceManager.GetString("Signal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string Start_Text {
            get {
                return ResourceManager.GetString("Start_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string StartTime_Text {
            get {
                return ResourceManager.GetString("StartTime_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string State_Text {
            get {
                return ResourceManager.GetString("State_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步距 的本地化字符串。
        /// </summary>
        internal static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Stop_Text {
            get {
                return ResourceManager.GetString("Stop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string System_Text {
            get {
                return ResourceManager.GetString("System_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扭力 的本地化字符串。
        /// </summary>
        internal static string Torque {
            get {
                return ResourceManager.GetString("Torque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取扭力 的本地化字符串。
        /// </summary>
        internal static string Torque_Text {
            get {
                return ResourceManager.GetString("Torque_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X轴 的本地化字符串。
        /// </summary>
        internal static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y轴 的本地化字符串。
        /// </summary>
        internal static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Z轴 的本地化字符串。
        /// </summary>
        internal static string ZAxis {
            get {
                return ResourceManager.GetString("ZAxis", resourceCulture);
            }
        }
    }
}
